"""empty message

Revision ID: 3a5ccb3c7e8
Revises: None
Create Date: 2015-09-18 14:57:18.642923

"""

# revision identifiers, used by Alembic.
revision = '3a5ccb3c7e8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('author', sa.Unicode(), nullable=True),
    sa.Column('last_commit_date', sa.DateTime(), nullable=True),
    sa.Column('last_commit_message', sa.Unicode(), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    ### end Alembic commands ###
