"""empty message

Revision ID: 45c049a62ee
Revises: 6be10bc7d4
Create Date: 2015-09-18 15:47:00.903454

"""

# revision identifiers, used by Alembic.
revision = '45c049a62ee'
down_revision = '6be10bc7d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('another_column', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'another_column')
    ### end Alembic commands ###
